## TRAVAIL SUR EAU DU ROBINET

In [1]:
import pandas as pd
pd.set_option("display.max_columns", None)  # show all cols
pd.set_option("display.max_colwidth", None)  # show full width of showing cols
pd.set_option(
    "display.expand_frame_repr", False
)

In [2]:
edr_cap_res = pd.read_csv(r'C:\Users\EPPINGER Muriel\Documents\D4G_13\EDR\CAP_RES_202412.txt', delimiter=',')

C:\Users\EPPINGER Muriel\AppData\Local\Temp\ipykernel_23764\710753745.py:1: DtypeWarning: Columns (0,1,2,5,8) have mixed types. Specify dtype option on import or set low_memory=False.
  edr_cap_res = pd.read_csv(r'C:\Users\EPPINGER Muriel\Documents\D4G_13\EDR\CAP_RES_202412.txt', delimiter=',')

In [3]:
edr_cap_plv = pd.read_csv(r'C:\Users\EPPINGER Muriel\Documents\D4G_13\EDR\CAP_PLV_202412.txt', delimiter=',')

In [4]:
# période de la BDD EDR_UDI

print(edr_cap_plv['dateprel'].min())
print(edr_cap_plv['dateprel'].max())

2015-09-08
2024-12-31

In [7]:
# extraction d'une referenceprel dnas bdd "prélèvements"

edr_cap_plv.loc[edr_cap_plv['referenceprel']=='00100143315',:]

  distrcode                                                   distrlib    distrsiret cddept inseecommune nomcommune   cdreseau          nomreseau codetypeinstallation nomtypeinstallation inae    cdpointsurv             nompointsurv referenceprel    dateprel heureprel finaliteprel                                                                                            conclusionprel cdtypeeau              libtypeeau plvconformitebacterio plvconformitechimique plvcomplet plvcdorganismepayeur typevisite plvcondition       preleveur   distrsiren plvconformiterefbacterio plvconformiterefchimique  cddeptsandre dtautorisation champcaptant    codebrgm codebss     dmajplv   dmodifplv   dmodifins representativite  coord_x  coord_y
0  00101028  SERA - SYNDICAT DES EAUX DE LA REGION D'AMBERIEU-EN-BUGEY  2.501018e+13    001        01007   AMBRONAY  001000060  PUITS DU BELLATON                  CAP             CAPTAGE  ESO  0010000000062  PUITS DU BELLATON (SUD)   00100143315  2024-11-25     09h52           CS  Eau brute souterraine conforme aux limites de qualité en vigueur pour l'ensemble des paramètres mesurés.        B   EAU BRUTE SOUTERRAINE                      C                     C          O             00100452  RP                 NaN  13000807100107  250101839.0                        C                        C             1     1967-09-06            N  06754X0040     NaN  2024-12-10  2024-12-11  2025-01-06                O      NaN      NaN

In [9]:
# modification format reference prel pour comparaison avec autres bdd

edr_cap_res['referenceprel']=edr_cap_res['referenceprel'].astype('string')
edr_cap_res['referenceprel']=edr_cap_res['referenceprel'].apply(lambda x : '00'+x if len(x) == 9
                                                                 else '0'+x  if len(x) == 10
                                                                 else x)

In [10]:
# extraction d'un prélèvement dans bdd resultats

edr_cap_res.loc[edr_cap_res['referenceprel']=='00100143315',:]

     cddept referenceprel    cdanalyse refechantillonlabo datereceptionechant cdlaboratoire   laboratoire cdtypeanalyse analysecdorganisme analysedate insituana  cdparametre cdparametresiseeaux   rqana rssigne  rsana cdunitereferencesiseeaux cdunitereference  cdfractionanalyse  sandrelaboratoire representativite
2333      1   00100143315  100152348.0      LSE2411-32591          2024-11-25        6901.0  4.105453e+13        0011RP           100452.0  2024-12-06         L       1141.0                 24D  <0,020       <   0.00                     µg/L              133                NaN              217.0                O
2334      1   00100143315  100152348.0      LSE2411-32591          2024-11-25        6901.0  4.105453e+13        0011RP           100452.0  2024-12-06         L       2011.0               26DCB  <0,005       <   0.00                     µg/L              133                NaN              217.0                O
2335      1   00100143315  100152348.0      LSE2411-32591          2024-11-25        6901.0  4.105453e+13        0011RP           100452.0  2024-12-06         L       8865.0             471811R   0,020     NaN   0.02                     µg/L              133                NaN              217.0                O
2336      1   00100143315  100152348.0      LSE2411-32591          2024-11-25        6901.0  4.105453e+13        0011RP           100452.0  2024-12-06         L       1832.0                 A2H  <0,020       <   0.00                     µg/L              133                NaN              217.0                O
2337      1   00100143315  100152348.0      LSE2411-32591          2024-11-25        6901.0  4.105453e+13        0011RP           100452.0  2024-12-06         L       2007.0             ABAMECT  <0,020       <   0.00                     µg/L              133                NaN              217.0                O
...     ...           ...          ...                ...                 ...           ...           ...           ...                ...         ...       ...          ...                 ...     ...     ...    ...                      ...              ...                ...                ...              ...
2660      1   00100143315  100152348.0      LSE2411-32591          2024-11-25        6901.0  4.105453e+13        0011RP           100452.0  2024-12-06         L       2096.0             TRINEXA  <0,020       <   0.00                     µg/L              133                NaN              217.0                O
2661      1   00100143315  100152348.0      LSE2411-32591          2024-11-25        6901.0  4.105453e+13        0011RP           100452.0  2024-12-06         L       7087.0               TRITO  <0,020       <   0.00                     µg/L              133                NaN              217.0                O
2662      1   00100143315  100152348.0      LSE2411-32591          2024-11-25        6901.0  4.105453e+13        0011RP           100452.0  2024-12-06         L       1295.0             TURBNFU    <0,1       <   0.00                      NFU              232                NaN              217.0                O
2663      1   00100143315  100152348.0      LSE2411-32591          2024-11-25        6901.0  4.105453e+13        0011RP           100452.0  2024-12-06         L       7521.0              ZCYINE  <0,005       <   0.00                     µg/L              133                NaN              217.0                O
2664      1   00100143315  100152348.0      LSE2411-32591          2024-11-25        6901.0  4.105453e+13        0011RP           100452.0  2024-12-06         L       2858.0             ZOXAMID  <0,005       <   0.00                     µg/L              133                NaN              217.0                O

[332 rows x 21 columns]

Vérification faite le prélèvement '00100143315' n'est pas présent dans la base EDR_UDI

In [11]:
# recherche de doublons dans la base des résultats

doublons = edr_cap_res.duplicated()
df_doublons_res = edr_cap_res[doublons]
print(df_doublons_res)

Empty DataFrame
Columns: [cddept, referenceprel, cdanalyse, refechantillonlabo, datereceptionechant, cdlaboratoire, laboratoire, cdtypeanalyse, analysecdorganisme, analysedate, insituana, cdparametre, cdparametresiseeaux, rqana, rssigne, rsana, cdunitereferencesiseeaux, cdunitereference, cdfractionanalyse, sandrelaboratoire, representativite]
Index: []

In [12]:
# recherche de doublons dans la base des prélevements

doublons = edr_cap_plv.duplicated()
df_doublons_plv = edr_cap_plv[doublons]
print(df_doublons_plv)

Empty DataFrame
Columns: [distrcode, distrlib, distrsiret, cddept, inseecommune, nomcommune, cdreseau, nomreseau, codetypeinstallation, nomtypeinstallation, inae, cdpointsurv, nompointsurv, referenceprel, dateprel, heureprel, finaliteprel, conclusionprel, cdtypeeau, libtypeeau, plvconformitebacterio, plvconformitechimique, plvcomplet, plvcdorganismepayeur, typevisite, plvcondition, preleveur, distrsiren, plvconformiterefbacterio, plvconformiterefchimique, cddeptsandre, dtautorisation, champcaptant, codebrgm, codebss, dmajplv, dmodifplv, dmodifins, representativite, coord_x, coord_y]
Index: []

In [13]:
# création d'une liste unique de referenceprel

edr_plv = edr_cap_plv[['referenceprel']].copy()
unique_edr_plv=edr_plv.drop_duplicates()
unique_edr_plv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2720 entries, 0 to 2719
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   referenceprel  2720 non-null   object
dtypes: object(1)
memory usage: 21.4+ KB

In [14]:
# recherche liste unique referenceprel/cdparametres/SISEEAUX

ref_param = edr_cap_res[['referenceprel','cdparametre','cdparametresiseeaux']].copy()
unique_edr_param=ref_param.drop_duplicates()
unique_edr_param.info()

<class 'pandas.core.frame.DataFrame'>
Index: 425845 entries, 0 to 426614
Data columns (total 3 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   referenceprel        425845 non-null  object
 1   cdparametre          425172 non-null  float64
 2   cdparametresiseeaux  424878 non-null  object
dtypes: float64(1), object(2)
memory usage: 13.0+ MB

## TRAVAIL SUR EAU DE COMMUNE

In [16]:
import duckdb
from pipelines.tasks._common import DUCKDB_FILE

con = duckdb.connect(database=DUCKDB_FILE, read_only=True)

In [17]:
query_2024 = """
SELECT * from edc_prelevements
"""

edc_plv = con.sql(query_2024)
data_edc_plv = edc_plv.df()
data_edc_plv.head(2)

  cddept   cdreseau inseecommuneprinc nomcommuneprinc cdreseauamont nomreseauamont pourcentdebit referenceprel   dateprel heureprel                                                                                           conclusionprel                         ugelib                        distrlib                          moalib plvconformitebacterio plvconformitechimique plvconformitereferencebact plvconformitereferencechim  de_partition de_ingestion_date
0    001  001000003             01007        AMBRONAY          None           None          None   00100087319 2016-02-22     11h07  Eau d'alimentation conforme aux exigences de qualité en vigueur pour l'ensemble des paramètres mesurés.  SI REGION D'AMBERIEU-EN-BUGEY  SIE REGION D'AMBERIEU-EN-BUGEY  SIE REGION D'AMBERIEU-EN-BUGEY                     C                     C                          C                          C          2016        2025-02-08
1    001  001000003             01007        AMBRONAY          None           None          None   00100087349 2016-02-22     10h21  Eau d'alimentation conforme aux exigences de qualité en vigueur pour l'ensemble des paramètres mesurés.  SI REGION D'AMBERIEU-EN-BUGEY  SIE REGION D'AMBERIEU-EN-BUGEY  SIE REGION D'AMBERIEU-EN-BUGEY                     C                     C                          C                          C          2016        2025-02-08

In [19]:
exple = """
SELECT * from edc_prelevements
WHERE referenceprel='00100143315'
"""

edc_plv_exple = con.sql(exple)
data_edc_plv_exple = edc_plv_exple.df()
data_edc_plv_exple

Empty DataFrame
Columns: [cddept, cdreseau, inseecommuneprinc, nomcommuneprinc, cdreseauamont, nomreseauamont, pourcentdebit, referenceprel, dateprel, heureprel, conclusionprel, ugelib, distrlib, moalib, plvconformitebacterio, plvconformitechimique, plvconformitereferencebact, plvconformitereferencechim, de_partition, de_ingestion_date]
Index: []

In [20]:
exple_res = """
SELECT * from edc_resultats
WHERE referenceprel='00100143315'
"""

edc_res_exple = con.sql(exple_res)
data_edc_res_exple = edc_res_exple.df()
data_edc_res_exple

Empty DataFrame
Columns: [cddept, referenceprel, cdparametresiseeaux, cdparametre, libmajparametre, libminparametre, libwebparametre, qualitparam, insituana, rqana, cdunitereferencesiseeaux, cdunitereference, limitequal, refqual, valtraduite, casparam, referenceanl, de_partition, de_ingestion_date]
Index: []

La base EDR CAP ne semble pas être incluse dans la base EDC

# Réflexion à mener sur l'intégration ou non dans l'étude de la base EDR_CAP

In [ ]:
# Contenu base CAP  

edr_cap_res.describe(include='all')

          cddept referenceprel     cdanalyse refechantillonlabo datereceptionechant  cdlaboratoire   laboratoire cdtypeanalyse  analysecdorganisme analysedate insituana    cdparametre cdparametresiseeaux   rqana rssigne          rsana cdunitereferencesiseeaux cdunitereference  cdfractionanalyse  sandrelaboratoire representativite
count   426615.0        426615  4.167670e+05             416767              414403       416767.0  4.167670e+05        411250            416767.0      415711    426615  425942.000000              425648  426600  376655  425904.000000                   426613           426613               12.0       3.710900e+05           426615
unique      99.0          2719  2.911000e+03               2907                 138           49.0           NaN           455               791.0         150         2            NaN                1350    5490       8            NaN                       41               41                NaN                NaN                1
top         75.0   07700249174  7.700249e+09      LSE2411-25855          2024-11-20         6901.0           NaN        075RP7           7500034.0  2024-12-10         L            NaN                  PH  <0,005       <            NaN                     µg/L              133                NaN                NaN                O
freq     24386.0           675  6.700000e+02                670               18567       154208.0           NaN         19173             24222.0       22510    416767            NaN                2552  142888  375766            NaN                   377030           377030                NaN                NaN           426615
mean         NaN           NaN           NaN                NaN                 NaN            NaN  3.100525e+13           NaN                 NaN         NaN       NaN    2595.732144                 NaN     NaN     NaN       7.887604                      NaN              NaN               23.0       2.765410e+12              NaN
std          NaN           NaN           NaN                NaN                 NaN            NaN  1.524719e+13           NaN                 NaN         NaN       NaN    2043.104516                 NaN     NaN     NaN     239.931429                      NaN              NaN                0.0       5.700175e+12              NaN
min          NaN           NaN           NaN                NaN                 NaN            NaN  1.300021e+13           NaN                 NaN         NaN       NaN       0.000000                 NaN     NaN     NaN     -17.200000                      NaN              NaN               23.0       9.800000e+01              NaN
25%          NaN           NaN           NaN                NaN                 NaN            NaN  1.300190e+13           NaN                 NaN         NaN       NaN    1301.000000                 NaN     NaN     NaN       0.000000                      NaN              NaN               23.0       2.110000e+02              NaN
50%          NaN           NaN           NaN                NaN                 NaN            NaN  4.105453e+13           NaN                 NaN         NaN       NaN    1704.000000                 NaN     NaN     NaN       0.000000                      NaN              NaN               23.0       2.170000e+02              NaN
75%          NaN           NaN           NaN                NaN                 NaN            NaN  4.105453e+13           NaN                 NaN         NaN       NaN    2737.750000                 NaN     NaN     NaN       0.000000                      NaN              NaN               23.0       5.860000e+02              NaN
max          NaN           NaN           NaN                NaN                 NaN            NaN  7.788520e+13           NaN                 NaN         NaN       NaN   99999.000000                 NaN     NaN     NaN   52000.000000                      NaN              NaN               23.0       2.000132e+13              NaN

In [22]:
edr_cap_res['cdparametresiseeaux'].unique()

array(['24D', '26DCB', '471811R', ..., 'TTCB', 'ETOXAZ', 'TEMP_O2'],
      shape=(1351,), dtype=object)

2719 referenceprel en 2024

1350 paramètres SISEEAUX